# Overall title for pages.
title: 'R for Social Scientists'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: ''

# Comma-separated list of keywords for the lesson
keywords: 'software, data, lesson, The Carpentries'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable'

# Who to contact if there are any issues
contact: 'pawanjangra1198@gmail.com'


# Order of episodes in your lesson
episodes: 
- 00-intro.Rmd
- 01-intro-to-r.Rmd
- 02-starting-with-data.Rmd
- data-types.Rmd
- data-frame.Rmd
- 03-dplyr.Rmd
- 04-tidyr.Rmd
- reshaping-data.Rmd
- 05-ggplot2.Rmd
- 06-rmarkdown.Rmd
- 07-json.Rmd


# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live
